version: '3'

services:
  ylva-vision-api:
    build: .
    # command: uvicorn api.camera_server_broadcast:app --host 0.0.0.0 --port 8000
    # command: python api/camera_server_broadcast.py
    tty: true
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    working_dir: /app
    environment:
      - PULSE_SERVER=/mnt/wslg/PulseServer
      - DISPLAY=$DISPLAY
      # - PULSE_SERVER=$PULSE_SERVER
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
    ports:
      - "8000:8000"
    # devices:
    #   - "/dev/video0:/dev/video0"